---
- name: Set default redis image
  ansible.builtin.set_fact:
    _default_redis_image: "{{ _redis_image }}:{{ _redis_image_version }}"

- name: Set user provided redis image
  ansible.builtin.set_fact:
    _custom_redis_image: "{{ redis_image }}:{{ redis_image_version }}"
  when:
    - redis_image | default([]) | length
    - redis_image_version is defined or redis_image_version != ''

- name: Set Redis image URL
  ansible.builtin.set_fact:
    _redis_image: "{{ _custom_redis_image | default(lookup('env', 'RELATED_IMAGE_EDA_REDIS')) | default(_default_redis_image, true) }}"

- name: Combine the default settings with custom values from the resource
  ansible.builtin.set_fact:
    combined_redis: "{{ _redis | combine(redis, recursive=True) }}"

- name: Redis Deployment & Service
  kubernetes.core.k8s:
    state: present
    apply: true
    wait: false
    definition: "{{ lookup('template', 'templates/' + item + '.yaml.j2') | from_yaml }}"
  loop:
    - 'redis.service'
    - 'redis.deployment'
  no_log: "{{ no_log }}"
