---
- name: Get the current resource pod information.
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: '{{ ansible_operator_meta.namespace }}'
    label_selectors:
      - "app.kubernetes.io/name={{ ansible_operator_meta.name }}"
      - "app.kubernetes.io/managed-by={{ deployment_type }}-operator"
      - "app.kubernetes.io/component={{ deployment_type }}-api"
    field_selectors:
      - status.phase=Running
  register: eda_api_pod

- name: Set the resource pod name as a variable.
  set_fact:
    eda_api_pod_name: "{{ eda_api_pod['resources'][0]['metadata']['name'] | default('') }}"

- name: Run DB Migrations k8s job
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'migration-job.yaml.j2') }}"
    wait: yes
    wait_condition:
      status: "True"
      type: Complete
  register: migration_job_result

- name: Apply deployment resources
  k8s:
    apply: yes
    definition: "{{ lookup('template', item + '.yaml.j2') }}"
    wait: yes
  loop:
    - 'eda.configmap'
    - 'eda-api.service'
    - 'eda-api.deployment'
    - 'eda-ui.service'
    - 'eda-ui.deployment'
    - 'eda-ui.ingress'
    - 'eda-worker.service'
    - 'eda-worker.deployment'
  register: this_deployment_result
