---

# API Image
- name: Set default eda api container image
  set_fact:
    _default_image: "{{ _image }}:{{ _image_version }}"

- name: Set user provided image
  set_fact:
    _custom_image: "{{ image }}:{{ image_version }}"
  when:
    - image | default([]) | length
    - image_version is defined or image_version != ''

- name: Set image URL
  set_fact:
    _image: >-
      {{ _custom_image |
         default(lookup('env', 'RELATED_IMAGE_EDA')) |
         default(_default_image, true) }}

# UI Image
- name: Set default eda ui container image
  set_fact:
    _default_image_web: "{{ _image_web }}:{{ _image_web_version }}"

- name: Set user provided image
  set_fact:
    _custom_image_web: "{{ image_web }}:{{ image_web_version }}"
  when:
    - image_web | default([]) | length
    - image_web_version is defined or image_web_version != ''

- name: Set image URL
  set_fact:
    _image_web: >-
      {{ _custom_image_web |
         default(lookup('env', 'RELATED_IMAGE_EDA_UI')) |
         default(_default_image_web, true) }}
