---

deployment_type: "eda"
_postgres_image: postgres
_postgres_image_version: 13

backup_api_version: '{{ deployment_type }}.ansible.com/v1alpha1'
backup_kind: 'EDABackup'

# set default secret names to be used if a backup dir and claim are provided (not a backup_name)
secret_key_secret: '{{ deployment_name }}-secret-key'
admin_password_secret: '{{ deployment_name }}-admin-password'
postgres_configuration_secret: '{{ deployment_name }}-postgres-configuration'
supported_pg_version: 13
