---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - automationeda.ansible.com
  resources:
  - edas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automationeda.ansible.com
  resources:
  - edas/finalizers
  verbs:
  - update
- apiGroups:
  - automationeda.ansible.com
  resources:
  - edas/status
  verbs:
  - get
  - patch
  - update
