---
# defaults file for EDA

deployment_type: eda

no_log: true

_api_image: quay.io/ansible/eda-server
_api_image_version: latest

_ui_image: quay.io/ansible/eda-ui
_ui_image_version: latest

api:
  replicas: 1
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi

worker:
  replicas: 1
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi

ui:
  replicas: 1
  resource_requirements:
    requests:
      cpu: 200m
      memory: 512Mi

# Labels defined on the resource, which should be propagated to child resources
additional_labels: []
