---

- name: Determine and set postgres configuration secret and variables
  import_tasks: set_configuration_secret.yml

- name: Set default postgres image to be used
  import_tasks: set_image.yml

- name: Set variables to be used in Postgres templates
  import_tasks: set_variables.yml

- name: Create managed Postgres StatefulSet if no external db is defined
  import_tasks: create_managed_postgres.yml
  when: managed_database
