---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: edas.eda.ansible.com
spec:
  group: eda.ansible.com
  names:
    kind: EDA
    listKind: EDAList
    plural: edas
    singular: eda
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EDA is the Schema for the edas API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of EDA
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              additional_labels:
                description: Additional labels defined on the resource, which should be propagated to child resources
                type: array
                items:
                  type: string
              image_pull_policy:
                description: The image pull policy
                type: string
                default: IfNotPresent
                enum:
                - Always
                - always
                - Never
                - never
                - IfNotPresent
                - ifnotpresent
              image_pull_secrets:
                description: Image pull secrets for app and database containers
                type: array
                items:
                  type: string
              no_log:
                description: Configure no_log for no log tasks
                type: boolean
                default: true
              postgres:
                description: The EDA postgres StatefulSet
                properties:
                  resource_requirements:
                    description: Resource requirements for the EDA postgres container
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                    type: object
                type: object
              postgres_configuration_secret:
                description: Secret where the database configuration can be found
                type: string
              postgres_data_path:
                description: Path where the PostgreSQL data are located
                type: string
              postgres_extra_args:
                type: array
                items:
                  type: string
              postgres_image:
                description: Registry path to the PostgreSQL container to use
                type: string
              postgres_image_version:
                description: PostgreSQL container image version to use
                type: string
              postgres_priority_class:
                description: Assign a pre-existing priority class to the postgres pod
                type: string
              postgres_selector:
                description: nodeSelector for the Postgres pods
                type: string
              postgres_storage_class:
                description: Storage class to use for the PostgreSQL PVC
                type: string
              postgres_tolerations:
                description: node tolerations for the Postgres pods
                type: string
              service_account_annotations:
                description: ServiceAccount annotations
                type: string
              set_self_labels:
                description: Maintain some of the recommended `app.kubernetes.io/*` labels on the resource (self)
                type: boolean
                default: true
              service_type:
                description: The service type to be used on the deployed instance
                type: string
                enum:
                - LoadBalancer
                - loadbalancer
                - ClusterIP
                - clusterip
                - NodePort
                - nodeport
              ingress_type:
                description: The ingress type to use to reach the deployed instance
                type: string
                enum:
                - none
                - Ingress
                - ingress
                - Route
                - route
              ingress_api_version:
                description: The Ingress API version to use
                type: string
              ingress_path:
                description: The ingress path used to reach the deployed service
                type: string
              ingress_path_type:
                description: The ingress path type for the deployed service
                type: string
              ingress_annotations:
                description: Annotations to add to the Ingress Controller
                type: string
              ingress_tls_secret:
                description: Secret where the Ingress TLS secret can be found
                type: string
              ingress_class_name:
                description: The name of ingress class to use instead of the cluster default.
                type: string
              loadbalancer_protocol:
                description: Protocol to use for the loadbalancer
                type: string
                default: http
                enum:
                - http
                - https
              loadbalancer_port:
                description: Port to use for the loadbalancer
                type: integer
                default: 80
              route_host:
                description: The DNS to use to points to the instance
                type: string
              route_tls_termination_mechanism:
                description: The secure TLS termination mechanism to use
                type: string
                default: Edge
                enum:
                - Edge
                - edge
                - Passthrough
                - passthrough
              route_api_version:
                description: The route API version to use
                type: string
              route_tls_secret:
                description: Secret where the TLS related credentials are stored
                type: string
              nodeport_port:
                description: Port to use for the nodeport
                type: integer
          status:
            description: Status defines the observed state of EDA
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
