---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: edas.eda.ansible.com
spec:
  group: eda.ansible.com
  names:
    kind: EDA
    listKind: EDAList
    plural: edas
    singular: eda
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EDA is the Schema for the edas API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of EDA
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              additional_labels:
                description: Additional labels defined on the resource, which should be propagated to child resources
                type: array
                items:
                  type: string
              image_pull_policy:
                description: The image pull policy
                type: string
                default: IfNotPresent
                enum:
                - Always
                - always
                - Never
                - never
                - IfNotPresent
                - ifnotpresent
              image_pull_secrets:
                description: Image pull secrets for app and database containers
                type: array
                items:
                  type: string
              no_log:
                description: Configure no_log for no_log tasks
                type: boolean
                default: true
              postgres:
                description: The EDA postgres StatefulSet
                properties:
                  replicas:
                    description: The number of replicas for the deployment.
                    type: integer
                    default: 1
                    format: int32
                  resource_requirements:
                    description: Resource requirements for the EDA postgres container
                    properties:
                      requests:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                      limits:
                        properties:
                          cpu:
                            type: string
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                    type: object
                type: object
              postgres_configuration_secret:
                description: Secret where the database configuration can be found
                type: string
              postgres_data_path:
                description: Path where the PostgreSQL data are located
                type: string
              postgres_extra_args:
                type: array
                items:
                  type: string
              postgres_image:
                description: Registry path to the PostgreSQL container to use
                type: string
              postgres_image_version:
                description: PostgreSQL container image version to use
                type: string
              postgres_priority_class:
                description: Assign a pre-existing priority class to the postgres pod
                type: string
              postgres_selector:
                description: nodeSelector for the Postgres pods
                type: string
              postgres_storage_class:
                description: Storage class to use for the PostgreSQL PVC
                type: string
              postgres_tolerations:
                description: node tolerations for the Postgres pods
                type: string
              service_account_annotations:
                description: ServiceAccount annotations
                type: string
              set_self_labels:
                description: Maintain some of the recommended `app.kubernetes.io/*` labels on the resource (self)
                type: boolean
                default: true
          status:
            description: Status defines the observed state of EDA
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
