---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: edas.eda.ansible.com
spec:
  group: eda.ansible.com
  names:
    kind: EDA
    listKind: EDAList
    plural: edas
    singular: eda
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EDA is the Schema for the edas API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of EDA
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              no_log:
                description: Configure no_log for no_log tasks
                type: boolean
                default: true
              postgres_configuration_secret:
                description: Secret where the database configuration can be found
                type: string
              postgres_storage_class:
                description: Storage class to use for the PostgreSQL PVC
                type: string
          status:
            description: Status defines the observed state of EDA
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
