---

name: Build Operator Image

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push main image
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and Push Image
        run: |
          IMG=quay.io/ansible/eda-server-operator:main make docker-buildx
