name: EDA-Operator PR
on:
  pull_request:
env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
jobs:
  validate-bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Validate OLM Bundle
        run: make bundle
